/*
 * Created by: egr
 * Created at: 03.05.2009
 * © 2007-2009 Alexander Egorov
 */

using System.Collections.Generic;
using Microsoft.Build.Framework;
using MSBuild.TeamCity.Tasks.Messages;

namespace MSBuild.TeamCity.Tasks
{
    /// <summary>
    /// Support for reporting tests in TeamCity from JUnit Ant task XML reports, 
    /// Maven Surefire XML reports, NUnit-Console XML reports. 
    /// Also supports reporting code inspections from FindBugs and PMD XML reports<p/>
    /// Starting with TeamCity 5.0, NUnit Test Launcher bundles support for .NET code coverage using NCover and PartCover coverage engines.<p/>
    /// Starting with TeamCity 5.1, supporting MSTest with Service Messages.<p/>
    /// If you prefer to call the FxCop tool directly from the script, not as a build runner, 
    /// you can use the this task to import an xml file generated by FxCopCmd tool into TeamCity.
    /// </summary>
    /// <example>Imports data from FxCop generated file
    /// <code><![CDATA[
    /// <ImportData
    ///     Type="FxCop"
    ///     Path="C:\FxCop.xml" 
    /// />
    /// ]]></code>
    /// Imports data from FxCop generated file full example (with all optional attributes)
    /// <code><![CDATA[
    /// <ImportData
    ///    IsAddTimestamp="true"
    ///    FlowId="1"
    ///    Type="FxCop"
    ///    Path="C:\FxCop.xml" 
    /// />
    /// ]]></code>
    /// Imports data from NCover generated file
    /// <code><![CDATA[
    /// <ImportData
    ///    Type="dotNetCoverage"
    ///    Path="C:\Ncover.xml" 
    ///    Tool="ncover" 
    /// />
    /// ]]></code>
    /// </example>
    public class ImportData : TeamCityTask
    {
        ///<summary>
        /// Initializes a new instance of the <see cref="ImportData"/> class
        ///</summary>
        public ImportData()
        {
        }

        ///<summary>
        /// Initializes a new instance of the <see cref="ImportData"/> class using 
        /// logger specified
        ///</summary>
        ///<param name="logger"><see cref="ILogger"/> implementation</param>
        public ImportData( ILogger logger )
            : base(logger)
        {
        }

        /// <summary>
        /// Gets or sets imported data type.<p/>
        /// <b>junit</b> for JUnit Ant task XML reports<br/>
        /// <b>surefire</b> for Maven Surefire XML reports<br/>
        /// <b>nunit</b> for NUnit-Console XML reports<br/>
        /// <b>findBugs</b> for FindBugs inspections XML reports<br/>
        /// <b>pmd</b> for PMD inspections XML reports<br/>
        /// <b>FxCop</b> for FxCop inspections XML reports<br/>
        /// <b>dotNetCoverage</b> Starting with TeamCity 5.0, NUnit Test Launcher bundles support for .NET code coverage using NCover and PartCover coverage engines.<br/>
        /// <b>mstest</b> for MSTest XML reports. Starting with TeamCity 5.1<br/>
        /// </summary>
        [Required]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets full path to data source file to import data from
        /// </summary>
        [Required]
        public string Path { get; set; }

        /// <summary>
        /// Gets or sets the tool name value can be partcover, ncover, or ncover3, depending on selected coverage tool in the coverage settings.
        /// </summary>
        public string Tool { get; set; }

        /// <summary>
        /// Reads TeamCity messages
        /// </summary>
        /// <returns>TeamCity messages list</returns>
        protected override IEnumerable<TeamCityMessage> ReadMessages()
        {
            yield return new ImportDataMessageBuilder(Tool, Path, Type).BuildMessage();
        }
    }
}