/*
 * Created by: egr
 * Created at: 03.05.2009
 * © 2007-2009 Alexander Egorov
 */

using Microsoft.Build.Framework;

namespace MSBuild.TeamCity.Tasks
{
	/// <summary>
	/// If you prefer to call the FxCop tool directly from the script, not as a build runner, 
	/// you can use the importData service messages to import an xml file generated by FxCopCmd tool into TeamCity.
	/// </summary>
	/// <example>Imports data from FxCop generated file
	/// <code><![CDATA[
	/// <ImportData
	///		Type="FxCop"
	///		Path="C:\FxCop.xml" 
	/// />
	/// ]]></code>
	/// mports data from FxCop generated file full example (with all optional attributes)
	/// <code><![CDATA[
	/// <ImportData
	///		IsAddTimestamp="true"
	///		FlowId="1"
	///		Type="FxCop"
	///		Path="C:\FxCop.xml" 
	/// />
	/// ]]></code>
	/// </example>
	public class ImportData : TeamCityTask
	{
		/// <summary>
		/// Get or sets imported data type. FxCop only supported at the moment
		/// </summary>
		[Required]
		public string Type { get; set; }

		/// <summary>
		/// Gets or sets full path to data source file to import data from
		/// </summary>
		[Required]
		public string Path { get; set; }

		/// <summary>
		/// When overridden in a derived class, executes the task.
		/// </summary>
		/// <returns>
		/// true if the task successfully executed; otherwise, false.
		/// </returns>
		public override bool Execute()
		{
			Write(new ImportDataTeamCityMessage(Type, Path));
			return true;
		}
	}
}