# version format
version: 2.5.{build}.0

# branches to build
branches:
  # whitelist
  only:
    - master
    - develop

# Do not build on tags (GitHub only)
skip_tags: true

# environment variables
environment:
  SignTool: C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\signtool.exe
  KeyFile: C:\projects\msbuildteamcitytasks\msbuildteamcitytasks.pfx
  SandCastleZipFile: C:\projects\msbuildteamcitytasks\SHFBInstaller.zip
  SandCastleUri: https://github.com/EWSoftware/SHFB/releases/download/v2015.5.2.0/SHFBInstaller_v2015.5.2.0.zip
  # this is how to set encrypted variable. Go to "Encrypt data" page in account menu to encrypt data.
  CertPassword:
    secure: QDWBD+3IIAYVFCfHFY7YCw==
  PfxUri:
    secure: 96Uy0sDkAp6sTkaD5MptudqaMXrjJkaBQhghxNHvaP9vHbUOcF1R9h9k3LXG6ZnwpxChllc+IbmK6KhExQVE1ae2ut5W3CjeeHjcHRDvlGXs4q2bDPVL455cH3ld6S3R

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

install:
    - ps: Start-FileDownload $env:PfxUri -FileName $env:KeyFile
    - ps: Start-FileDownload $env:SandCastleUri -FileName $env:SandCastleZipFile
    - cmd: nuget restore src\MSBuild.TeamCity.Tasks.sln
    - cmd: 7z x C:\projects\msbuildteamcitytasks\SHFBInstaller.zip
    - ps: msiexec /i C:\projects\msbuildteamcitytasks\InstallResources\SandcastleHelpFileBuilder.msi /quiet /qn /norestart /log install.log

platform: Any CPU

configuration: Release

build:
    project: src\MSBuild.TeamCity.Tasks.sln

test:
  assemblies:
    - Tests.dll

after_test:
    -cmd: msbuild src\MSBuildTeamCityTasks.shfbproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=%CONFIGURATION%
    -cmd: msbuild src\Setup\Setup.wixproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=%CONFIGURATION%
    -cmd: nuget pack src\msbuildteamcitytasks.nuspec -BasePath src -OutputDirectory src\MSBuild.TeamCity.Tasks\bin\%CONFIGURATION% -Version %APPVEYOR_BUILD_VERSION%

artifacts:
  - path: src\MSBuild.TeamCity.Tasks\bin\$(configuration)\*.nupkg

