/*
 * Created by: egr
 * Created at: 03.05.2009
 * © 2007-2009 Alexander Egorov
 */

using Microsoft.Build.Framework;

namespace MSBuild.TeamCity.Tasks
{
	/// <summary>
	/// Support for reporting tests in TeamCity from JUnit Ant task XML reports, 
	/// Maven Surefire XML reports, NUnit-Console XML reports. 
	/// Also supports reporting code inspections from FindBugs and PMD XML reports<p/>
	/// If you prefer to call the FxCop tool directly from the script, not as a build runner, 
	/// you can use the this task to import an xml file generated by FxCopCmd tool into TeamCity.
	/// </summary>
	/// <example>Imports data from FxCop generated file
	/// <code><![CDATA[
	/// <ImportData
	///		Type="FxCop"
	///		Path="C:\FxCop.xml" 
	/// />
	/// ]]></code>
	/// Imports data from FxCop generated file full example (with all optional attributes)
	/// <code><![CDATA[
	/// <ImportData
	///		IsAddTimestamp="true"
	///		FlowId="1"
	///		Type="FxCop"
	///		Path="C:\FxCop.xml" 
	/// />
	/// ]]></code>
	/// </example>
	public class ImportData : TeamCityTask
	{
		/// <summary>
		/// Get or sets imported data type.<p/>
		/// <b>junit</b> for JUnit Ant task XML reports<br/>
		/// <b>surefire</b> for Maven Surefire XML reports<br/>
		/// <b>nunit</b> for NUnit-Console XML reports<br/>
		/// <b>findBugs</b> for FindBugs inspections XML reports<br/>
		/// <b>pmd</b> for PMD inspections XML reports<br/>
		/// <b>FxCop</b> for FxCop inspections XML reports<br/>
		/// </summary>
		[Required]
		public string Type { get; set; }

		/// <summary>
		/// Gets or sets full path to data source file to import data from
		/// </summary>
		[Required]
		public string Path { get; set; }

		/// <summary>
		/// When overridden in a derived class, executes the task.
		/// </summary>
		/// <returns>
		/// true if the task successfully executed; otherwise, false.
		/// </returns>
		public override bool Execute()
		{
			Write(new ImportDataTeamCityMessage(Type, Path));
			return true;
		}
	}
}